name: Triggered on push from main

on:
  workflow_dispatch:

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print confirmation
        run: echo "Triggered REEEEEEEEEEEEEEEEEEEEEEEEEE"
